name: clustering
channels:
  - anaconda
  - conda-forge
  - omnia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alembic=1.2.1
  - asn1crypto=0.24.0
  - attrs=19.2.0
  - backcall=0.1.0
  - bcrypt=3.1.6
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - idna=2.8
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9c
  - json5=0.8.5
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jupyterlab=1.1.4
  - jupyterlab_code_formatter=0.5.2
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.5
  - libsodium=1.0.17
  - libstdcxx-ng=9.1.0
  - libuuid=2.32.1
  - libuv=1.32.0
  - libxcb=1.13
  - libxml2=2.9.9
  - mako=1.1.0
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - msgpack-python=0.6.2
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - nodejs=12.11.1
  - notebook=6.0.1
  - numpy=1.17.2
  - openssl=1.1.1c
  - pandas=0.25.1
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pint=0.9
  - pip=19.2.3
  - plotly=4.1.1
  - postgresql=11.5
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - psycopg2=2.8.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py-cpuinfo=5.0.0
  - py3dmol=0.8.0
  - pycparser=2.19
  - pydantic=0.32.2
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-editor=1.0.4
  - pytz=2019.2
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qcelemental=0.9.0
  - qcengine=0.11.0
  - qcfractal=0.11.0
  - qcportal=0.11.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=8.0
  - requests=2.22.0
  - retrying=1.3.3
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.2.0
  - sip=4.19.8
  - six=1.12.0
  - sqlalchemy=1.3.8
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=4.3.2
  - tzcode=2019a
  - urllib3=1.25.6
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yaml=0.1.7
  - yapf=0.28.0
  - zeromq=4.3.2
  - zlib=1.2.11
